### ISSUE TITLE
SQLite 설치 관련 이슈

### ISSUE THREAD

**Issue by eunchan-park** [SWE3003-41/ClassMaterial#1]
안녕하세요, 데이터베이스 프로젝트 수강하는 박은찬이라고 합니다.

올려주신 매뉴얼대로 SQLite 설치를 시도하였는데 make 가 실패합니다.

우분투 초기상태에서 git, gcc, make 까지 설치한 상태입니다.

번거롭게 해서 죄송하고 신경써주셔서 감사드립니다.

![image](https://user-images.githubusercontent.com/31975515/64221308-576d1c80-cf07-11e9-90c0-83b3e163da35.png)

**Comment by Csoyee** [comment]
안녕하세요 과목 조교 최소이입니다.

에러메세지에서 확인할 수 있 듯 `tclsh: not found`  문제인 것 같습니다. 
tcl 패키지를 설치해보고 configure 과정부터 다시 수행해보시면 될 것 같습니다.   

`sudo apt-get install tcl`

**Comment by eunchan-park** [comment]
해결되었습니다. 감사합니다.
